apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      run: apache-app
  template:
    metadata:
      labels:
        run: apache-app
    spec:
      containers:
      - name: apache-app
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: default
  labels:
    run: apache-app
spec:
  ports:
  - port: 80
  selector:
    run: apache-app

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deploy

# ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/